name: "Close stale issues and PRs "

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v10
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

          days-before-stale: 30
          days-before-close: 30

          stale-issue-message: |
             This issue has been inactive for a while.
            It will be closed in 30 days if no further activity occurs.

          stale-pr-message: |
             This pull request has been inactive for a while.
            It will be closed in 30 days if no further activity occurs.

          close-issue-message: |
             Closing this issue due to 30 days of inactivity after being marked stale.

          close-pr-message: |
             Closing this pull request due to 30 days of inactivity after being marked stale.

          stale-issue-label: "stale"
          stale-pr-label: "stale"

          exempt-issue-labels: "bug,duplicate,enhancement,FYI - Docs,help-needed,inactive,Needs More Info,question,wontfix"
          exempt-pr-labels: "bug,duplicate,enhancement,FYI - Docs,help-needed,inactive,Needs More Info,question,wontfix"

          exempt-all-milestones: true
          exempt-all-assignees: true

          operations-per-run: 200
